import type { Bag, Order } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id) || PlaceHolderImages[0];

export const bags: Bag[] = [
  {
    id: '1',
    name: 'Midnight Bloom Tote',
    price: 129.99,
    description: 'An elegant leather tote bag in classic black, perfect for both office and evening wear. Features a spacious interior and multiple pockets.',
    imageUrl: getImage('1').imageUrl,
    imageHint: getImage('1').imageHint,
    type: 'Tote',
    brand: 'ChicVogue',
  },
  {
    id: '2',
    name: 'Sahara Crossbody',
    price: 89.99,
    description: 'A chic and versatile crossbody bag in a neutral beige. Its compact design makes it ideal for weekend outings.',
    imageUrl: getImage('2').imageUrl,
    imageHint: getImage('2').imageHint,
    type: 'Crossbody',
    brand: 'LuxeCarry',
  },
  {
    id: '3',
    name: 'Urban Explorer Backpack',
    price: 159.99,
    description: 'A spacious and durable canvas backpack designed for the modern commuter. Includes a padded laptop sleeve.',
    imageUrl: getImage('3').imageUrl,
    imageHint: getImage('3').imageHint,
    type: 'Backpack',
    brand: 'UrbanTote',
  },
  {
    id: '4',
    name: 'Starlight Clutch',
    price: 79.99,
    description: 'A stylish and shimmering clutch for evening events. Comes with a detachable silver chain strap.',
    imageUrl: getImage('4').imageUrl,
    imageHint: getImage('4').imageHint,
    type: 'Clutch',
    brand: 'Eleganté',
  },
  {
    id: '5',
    name: 'Heritage Satchel',
    price: 189.99,
    description: 'A timeless satchel bag crafted from rich brown leather, featuring classic buckle details and an adjustable shoulder strap.',
    imageUrl: getImage('5').imageUrl,
    imageHint: getImage('5').imageHint,
    type: 'Satchel',
    brand: 'ChicVogue',
  },
  {
    id: '6',
    name: 'Azure Dream Hobo',
    price: 119.99,
    description: 'A modern hobo bag in a beautiful blue hue, with a relaxed silhouette and a comfortable, wide shoulder strap.',
    imageUrl: getImage('6').imageUrl,
    imageHint: getImage('6').imageHint,
    type: 'Hobo',
    brand: 'LuxeCarry',
  },
  {
    id: '7',
    name: 'Wanderer Mini Backpack',
    price: 99.99,
    description: 'A compact and trendy mini backpack perfect for light travel and daily essentials. Made from water-resistant nylon.',
    imageUrl: getImage('7').imageUrl,
    imageHint: getImage('7').imageHint,
    type: 'Backpack',
    brand: 'UrbanTote',
  },
  {
    id: '8',
    name: 'Opulent Shoulder Bag',
    price: 149.99,
    description: 'A versatile shoulder bag with striking gold hardware and a structured shape. Can be worn for any occasion.',
    imageUrl: getImage('8').imageUrl,
    imageHint: getImage('8').imageHint,
    type: 'Tote',
    brand: 'Eleganté',
  },
  {
    id: '9',
    name: 'Metro Fanny Pack',
    price: 69.99,
    description: 'A sporty yet stylish fanny pack for hands-free convenience. Features an adjustable strap and secure zip pockets.',
    imageUrl: getImage('9').imageUrl,
    imageHint: getImage('9').imageHint,
    type: 'Crossbody',
    brand: 'UrbanTote',
  },
  {
    id: '10',
    name: 'Ruby Radiance Handbag',
    price: 139.99,
    description: 'A structured top-handle bag in a vibrant red that makes a bold statement. Includes an optional crossbody strap.',
    imageUrl: getImage('10').imageUrl,
    imageHint: getImage('10').imageHint,
    type: 'Satchel',
    brand: 'ChicVogue',
  },
  {
    id: '11',
    name: 'Sunset Straw Tote',
    price: 75.00,
    description: 'A bohemian-style woven straw tote, perfect for beach days and summer markets. Lined with soft cotton.',
    imageUrl: getImage('11').imageUrl,
    imageHint: getImage('11').imageHint,
    type: 'Tote',
    brand: 'LuxeCarry',
  },
  {
    id: '12',
    name: 'Executive Laptop Bag',
    price: 199.99,
    description: 'A professional and sleek laptop bag with multiple compartments for organization. Fits up to a 15-inch laptop.',
    imageUrl: getImage('12').imageUrl,
    imageHint: getImage('12').imageHint,
    type: 'Satchel',
    brand: 'Eleganté',
  },
  {
    id: '13',
    name: 'Tary Satchel Bag',
    price: 16.65,
    description: ' Adjustable & Detachable Straps Solid Coloring',
    imageUrl: getImage('13').imageUrl,
    imageHint: getImage('13').imageHint,
    type: 'Satchel',
    brand: 'Les Catino',
  },
  {
    id: '14',
    name: 'Under Armour',
    price: 32.65,
    description: '100% Polyester',
    imageUrl: getImage('14').imageUrl,
    imageHint: getImage('14').imageHint,
    type: 'Tote bag',
    brand: 'Under Armour',
  },
];

export const orders: Order[] = [
  {
    id: 'ORD-12345',
    date: '2024-07-20',
    items: [
      { bag: bags[0], quantity: 1 },
      { bag: bags[3], quantity: 1 },
    ],
    total: 209.98,
    status: 'Delivered',
    deliveryOption: 'Standard',
  },
  {
    id: 'ORD-67890',
    date: '2024-07-28',
    items: [{ bag: bags[2], quantity: 1 }],
    total: 159.99,
    status: 'Shipped',
    deliveryOption: 'Express',
  },
  {
    id: 'ORD-13579',
    date: '2024-08-01',
    items: [{ bag: bags[8], quantity: 2 }],
    total: 139.98,
    status: 'Processing',
    deliveryOption: 'Standard',
  },
];
